services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:?Configure DB_USER no .env}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Configure DB_PASSWORD no .env}
      POSTGRES_DB: ${DB_NAME:?Configure DB_NAME no .env}
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
